
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SrceApplicaton.Models
{

using System;
    using System.Collections.Generic;
    
public partial class JobTemplates
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public JobTemplates()
    {
        this.Job = new HashSet<Job>();
    }


    public byte TemplateID { get; set; }

    public Nullable<byte> Chairs { get; set; }

    public string ChairLayout { get; set; }

    public Nullable<byte> Tables { get; set; }

    public string TablesLayout { get; set; }

    public string ExtraNotes { get; set; }

    public bool Wall { get; set; }

    public string Hall { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Job> Job { get; set; }

}

}
