
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SrceApplicaton.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TechnicianStats
{

    public short StatsID { get; set; }

    public Nullable<short> WorkHours { get; set; }

    public Nullable<short> ThisMonthSalary { get; set; }

    public Nullable<short> ThisYearSalary { get; set; }

    public Nullable<short> LastMonthSalary { get; set; }

}

}
